ASSEMBLY_A=NDesk.DBus.dll
ASSEMBLY_B=NDesk.DBus.GLib.dll
SOURCES_A=$(wildcard dbus-sharp/*.cs)
SOURCES_B=$(wildcard dbus-sharp-glib/*.cs)
REFERENCES=-r:System -r:System.Xml -r:Mono.Posix

all: $(ASSEMBLY_A) $(ASSEMBLY_B)

$(ASSEMBLY_A): $(SOURCES_A)
	gmcs -out:$@ -debug -unsafe -target:library $(REFERENCES) $(SOURCES_A)

$(ASSEMBLY_B): $(ASSEMBLY_A) $(SOURCES_B)
	gmcs -out:$@ -debug -unsafe -target:library -r:NDesk.DBus.dll $(REFERENCES) $(SOURCES_B)

clean:
	rm -f *.{dll,mdb}

