# DISTRIBUTION BRANDING BUILD HOOK
# 
# The basic installation must leave a branding.dll file
# installed in $(pkglibdir). The entry branding class must
# implement Banshee.Base.ICustomBranding
#
# ASSEMBLY = branding.dll
# brandingdir = $(pkglibdir)
# branding_SCRIPTS = $(ASSEMBLY)
#

