ASSEMBLY=Hal.dll
SOURCES=$(wildcard *.cs)
REFERENCES=-r:NDesk.DBus.dll

$(ASSEMBLY): $(SOURCES)
	cp ../dbus-sharp/NDesk.DBus.dll .
	gmcs -out:$@ -debug -unsafe -target:library $(REFERENCES) $(SOURCES)

clean:
	rm -f *.{dll,mdb}

