.TH BANSHEE "1" "June 2009" "Banshee 1.4.3 (1.4.3) http://banshee-project.org" "User Commands"
.SH NAME
Banshee \- Media Management and Playback application
.
.br
Muinshee \- Media Management and Playback application
.SH SYNOPSIS
.B banshee-1
[\fIoptions\fR...] [\fIfiles|URIs\fR...]
.
.br
.B muinshee
[\fIoptions\fR...] [\fIfiles|URIs\fR...]
.SH DESCRIPTION
Banshee is an media management and playback application for the GNOME desktop, allowing users to import audio from CDs, search their library, create playlists of selections of their library, sync music to/from iPods and other media devices, play and manage video files and burn selections to a CD. 
.SH OPTIONS
.TP
\fB\-\-next\fR
Play the next track, optionally restarting if the
\&'restart' value is set
.TP
\fB\-\-previous\fR
Play the previous track, optionally restarting if
the 'restart value is set
.TP
\fB\-\-play\-enqueued\fR
Automatically start playing any tracks enqueued on
the command line
.TP
\fB\-\-play\fR
Start playback
.TP
\fB\-\-pause\fR
Pause playback
.TP
\fB\-\-stop\fR
Completely stop playback
.TP
\fB\-\-stop\-when\-finished\fR
Enable or disable playback stopping after the
currently playing track (value should be either
\&'true' or 'false')
.TP
\fB\-\-set\-volume\fR=\fILEVEL\fR
Set the playback volume (0\-100)
.TP
\fB\-\-set\-position\fR=\fIPOS\fR
Seek to a specific point (seconds, float)
.TP
\fB\-\-query\-current\-state\fR
Print current player state
.TP
\fB\-\-query\-last\-state\fR
Print last player state
TP
\fB\-\-query\-can\-pause\fR
Query whether the player can be paused
.TP
\fB\-\-query\-can\-seek\fR
Query whether the player can seek
.TP
\fB\-\-query\-volume\fR
Print player volume
.TP
\fB\-\-query\-position\fR
Print player position in currently playing track
.TP
\fB\-\-query\-uri\fR
Print URI of current track
.TP
\fB\-\-query\-artist\fR
Print artist name of current track
.TP
\fB\-\-query\-album\fR
Print album title of current track
.TP
\fB\-\-query\-title\fR
Print title of current track
.TP
\fB\-\-query\-duration\fR
Print duration of current track
.TP
\fB\-\-query\-track\-number\fR
Print track number of current track
.TP
\fB\-\-query\-track\-count\fR
Print album track count for current track
.TP
\fB\-\-query\-disc\fR
Print disc number of current track
.TP
\fB\-\-query\-year\fR
Print year of release of current track
.TP
\fB\-\-query\-rating\fR
Print user rating of current track
.TP
\fB\-\-show\fR|\fB\-\-present\fR
Present the user interface on the active workspace
.TP
\fB\-\-hide\fR
Hide the user interface
.TP
\fB\-\-no\-present\fR
Do not present the user interface, regardless of
any other options
.TP
\fB\-\-debug\fR
Enable general debugging features
.TP
\fB\-\-debug\-sql\fR
Enable debugging output of SQL queries
.TP
\fB\-\-debug\-addins\fR
Enable debugging output of Mono.Addins
.TP
\fB\-\-db\fR=\fIFILE\fR
Specify an alternate database to use
.TP
\fB\-\-uninstalled\fR
Optimize instance for running uninstalled; most
notably, this will create an alternate Mono.Addins
database in the working directory
.TP
\fB\-\-disable\-dbus\fR
Disable DBus support completely
.TP
\fB\-\-no\-gtkrc\fR
Skip loading a custom gtkrc file
(~/.config/banshee\-1/gtkrc) if it exists
.TP
\fB\-\-help\fR
Show this help
.TP
\fB\-\-help\-playback\fR
Show options for controlling playback
.TP
\fB\-\-help\-query\-track\fR
Show options for querying the playing track
.TP
\fB\-\-help\-query\-player\fR
Show options for querying the playing engine
.TP
\fB\-\-help\-ui\fR
Show options for the user interface
.TP
\fB\-\-help\-debug\fR
Show options for developers and debugging
.TP
\fB\-\-help\-all\fR
Show all option groups
.TP
\fB\-\-version\fR
Show version information
.PP
Copyright 2005\-2009 Novell, Inc. and Contributors.
