# Must be run from parent directory

SUBDIRS = \
	ext/dbus-sharp \
	ext/hal-sharp \
	ext/taglib-sharp

all:
	for subdir in $(SUBDIRS); do \
		export PREV_PWD=$$(pwd); \
		cd $$subdir; \
		make -f Makefile.MonoDevelop; \
		cd $$PREV_PWD; \
	done

clean:
	for subdir in $(SUBDIRS); do \
		export PREV_PWD=$$(pwd); \
		cd $$subdir; \
		make -f Makefile.MonoDevelop clean; \
		cd $$PREV_PWD; \
	done

