# Must be run from parent directory

SUBDIRS = \
	ext/dbus-sharp \
	ext/hal-sharp \
	ext/taglib-sharp

all:
	for subdir in $(SUBDIRS); do \
		pushd $$subdir; \
		make -f Makefile.MonoDevelop; \
		popd; \
	done

clean:
	for subdir in $(SUBDIRS); do \
		pushd $$subdir; \
		make -f Makefile.MonoDevelop clean; \
		popd; \
	done

