#!/bin/bash

# This script will update all directories with svn:ignore
# You can still manage svn:ignore manually on directories
# If an ignore is found that is not in this script, it 
# will be kept on the directory

GLOBAL_IGNORES="Makefile
Makefile.in
*.exe
*.dll
*.config
*.mdb
*.schemas
*.pidb
*.user*"

ROOT_IGNORES="$GLOBAL_IGNORES
aclocal.m4
autom4te.cache
banshee.pc
config.*
configure
depcomp
install-sh
intltool-*
libtool
ltmain.sh
missing
mkinstalldirs
stamp-h1
snapshots
compile"

if [ -e autogen.sh ]; then
	DIR="."
else 
	DIR=".."
fi

pushd $DIR &>/dev/null

svn propset svn:ignore "$ROOT_IGNORES" .

for subdir in `find .`; do
	if [ ! -d $subdir ]; then
		continue
	elif [ `echo "$subdir" | grep .svn` ]; then
		continue
	elif [ ! `echo "$subdir" | grep -e "^./src"` ]; then
		continue
	fi

	existing="`svn propget svn:ignore $subdir`"
	IGNORE="$GLOBAL_IGNORES"

	for ex in $existing; do
		match=0
		for i in $IGNORE; do
			if [ "$i" = "$ex" ]; then
				match=1
			fi
		done
		if [ "$match" = "0" ]; then
			IGNORE="$IGNORE
$ex"
		fi
	done

	svn propset svn:ignore "$IGNORE" $subdir
done

popd &>/dev/null

