ASSEMBLY = TagLib.dll
SOURCES = \
	$(wildcard TagLib/*.cs) \
	$(wildcard TagLib/*/*.cs) \
	$(wildcard TagLib/*/*/*.cs)

$(ASSEMBLY): $(SOURCES)
	gmcs -out:$@ -debug -target:library $(SOURCES)

clean:
	rm -f *.{dll,mdb}

