/* -*- Mode: csharp; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: t -*- */
// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Nautilus {

	using System;

	public delegate void ActionChangedHandler(object o, ActionChangedArgs args);

	public class ActionChangedArgs : GLib.SignalArgs {
		public Nautilus.BurnRecorderActions Action{
			get {
				return (Nautilus.BurnRecorderActions) Args[0];
			}
		}

		public Nautilus.BurnRecorderMedia Media{
			get {
				return (Nautilus.BurnRecorderMedia) Args[1];
			}
		}

	}
}
