/* -*- Mode: csharp; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: t -*- */
// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Nautilus {

	using System;

	public delegate void AnimationChangedHandler(object o, AnimationChangedArgs args);

	public class AnimationChangedArgs : GLib.SignalArgs {
		public bool Spinning{
			get {
				return (bool) Args[0];
			}
		}

	}
}
