/* -*- Mode: csharp; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: t -*- */
// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Nautilus {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum BurnRecorderBlankFlags {

		None,
		DummyWrite = 1 << 1,
		Debug = 1 << 2,
	}
#endregion
}
