/* -*- Mode: csharp; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: t -*- */
// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Nautilus {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum BurnRecorderResponse {

		None,
		Cancel = -1,
		Erase = -2,
		Retry = -3,
	}
#endregion
}
