/* -*- Mode: csharp; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: t -*- */
// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Nautilus {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class BurnRecorderTrack : GLib.Opaque {

		public BurnRecorderTrack(IntPtr raw) : base(raw) {}

#endregion
#region Customized extensions
#line 1 "BurnRecorderTrack.custom"

	[DllImport("libnautilus-burn")]
	static extern void nautilus_burn_recorder_track_free(IntPtr raw);

	public void Free() {
		nautilus_burn_recorder_track_free(Handle);
	}

	[DllImport ("libnautilusburnglue")]
	private static extern IntPtr nautilus_burn_glue_create_track (string filename,
								      BurnRecorderTrackType type);

	public BurnRecorderTrack (string filename,
				  BurnRecorderTrackType type) {
		Raw = nautilus_burn_glue_create_track (filename, type);
	}

	~BurnRecorderTrack () {
		Free ();
	}

#endregion
	}
}
