/* -*- Mode: csharp; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: t -*- */
// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Nautilus {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum BurnRecorderWriteFlags {

		None,
		Eject = 1 << 0,
		Blank = 1 << 1,
		DummyWrite = 1 << 2,
		DiscAtOnce = 1 << 3,
		Debug = 1 << 4,
		Overburn = 1 << 5,
		Burnproof = 1 << 6,
	}
#endregion
}
