/* -*- Mode: csharp; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: t -*- */
// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Nautilus {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum BurnDriveType {

		File = 1 << 0,
		CdRecorder = 1 << 1,
		CdrwRecorder = 1 << 2,
		DvdRamRecorder = 1 << 3,
		DvdRwRecorder = 1 << 4,
		DvdPlusRRecorder = 1 << 5,
		DvdPlusRwRecorder = 1 << 6,
		CdDrive = 1 << 7,
		DvdDrive = 1 << 8,
	}
#endregion
}
