// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Nautilus {

	using System;

	public delegate void InsertMediaRequestHandler(object o, InsertMediaRequestArgs args);

	public class InsertMediaRequestArgs : GLib.SignalArgs {
		public bool IsReload{
			get {
				return (bool) Args[0];
			}
		}

		public bool CanRewrite{
			get {
				return (bool) Args[1];
			}
		}

		public bool Busy{
			get {
				return (bool) Args[2];
			}
		}

	}
}
