/* -*- Mode: csharp; tab-width: 4; c-basic-offset: 4; indent-tabs-mode: t -*- */
// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace NautilusSharp {

	using System;

#region Autogenerated code
	[GLib.CDeclCallback]
	internal delegate void CancelFuncNative(IntPtr data);

	internal class CancelFuncWrapper {

		public void NativeCallback (IntPtr data)
		{
			managed ();
		}

		internal CancelFuncNative NativeDelegate;
		Nautilus.CancelFunc managed;

		public CancelFuncWrapper (Nautilus.CancelFunc managed)
		{
			this.managed = managed;
			if (managed != null)
				NativeDelegate = new CancelFuncNative (NativeCallback);
		}

		public static Nautilus.CancelFunc GetManagedDelegate (CancelFuncNative native)
		{
			if (native == null)
				return null;
			CancelFuncWrapper wrapper = (CancelFuncWrapper) native.Target;
			if (wrapper == null)
				return null;
			return wrapper.managed;
		}
	}
#endregion
}
