// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Nautilus {

	using System;

	public delegate void WarnDataLossHandler(object o, WarnDataLossArgs args);

	public class WarnDataLossArgs : GLib.SignalArgs {
	}
}
