// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GtkSharpBackports {

	using System;

	public delegate void AboutDialogActivateLinkFunc(GtkSharpBackports.AboutDialog about, string link);

}
