// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GtkSharpBackports {

	using System;
	
	[GLib.CDeclCallback]
	internal delegate void AboutDialogActivateLinkFuncNative(IntPtr about, IntPtr link, IntPtr data);

	internal class AboutDialogActivateLinkFuncWrapper {

		public void NativeCallback (IntPtr about, IntPtr link, IntPtr data)
		{
			GtkSharpBackports.AboutDialog _arg0 = GLib.Object.GetObject(about) as GtkSharpBackports.AboutDialog;
			string _arg1 = GLib.Marshaller.Utf8PtrToString (link);
			managed ( _arg0,  _arg1);
		}

		internal AboutDialogActivateLinkFuncNative NativeDelegate;
		GtkSharpBackports.AboutDialogActivateLinkFunc managed;

		public AboutDialogActivateLinkFuncWrapper (GtkSharpBackports.AboutDialogActivateLinkFunc managed)
		{
			this.managed = managed;
			if (managed != null)
				NativeDelegate = new AboutDialogActivateLinkFuncNative (NativeCallback);
		}

		public static GtkSharpBackports.AboutDialogActivateLinkFunc GetManagedDelegate (AboutDialogActivateLinkFuncNative native)
		{
			if (native == null)
				return null;
			AboutDialogActivateLinkFuncWrapper wrapper = (AboutDialogActivateLinkFuncWrapper) native.Target;
			if (wrapper == null)
				return null;
			return wrapper.managed;
		}
	}
}
