// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace TotemPlParser {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[GLib.GType (typeof (TotemPlParser.ErrorGType))]
	public enum Error {

		Open,
		Write,
	}

	internal class ErrorGType {
		[DllImport ("totem-plparser.so.1")]
		static extern IntPtr totem_pl_parser_error_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (totem_pl_parser_error_get_type ());
			}
		}
	}
#endregion
}
