// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace TotemPlParser {

	using System;

	public delegate void IterFunc(Gtk.TreeModel model, Gtk.TreeIter iter, string uri, string title, out bool custom_title);

}
