// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace TotemPlParser {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum MediaType {

		Error = -1,
		Data = 1,
		CDDA,
		VCD,
		DVD,
	}
#endregion
}
