// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace TotemPlParser {

	using System;

	public delegate void PlaylistEndHandler(object o, PlaylistEndArgs args);

	public class PlaylistEndArgs : GLib.SignalArgs {
		public string Title{
			get {
				return (string) Args[0];
			}
		}

	}
}
