// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace TotemPlParser {

	using System;

	public delegate void PlaylistStartHandler(object o, PlaylistStartArgs args);

	public class PlaylistStartArgs : GLib.SignalArgs {
		public string Title{
			get {
				return (string) Args[0];
			}
		}

	}
}
