// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace TotemPlParser {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[GLib.GType (typeof (TotemPlParser.TypeGType))]
	public enum Type {

		PLS,
		M3U,
		M3U_DOS,
	}

	internal class TypeGType {
		[DllImport ("totem-plparser.so.1")]
		static extern IntPtr totem_pl_parser_type_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (totem_pl_parser_type_get_type ());
			}
		}
	}
#endregion
}
