#!/bin/bash

DB_FILE="$HOME/.config/banshee-1/banshee.db"
test ! -z $1 -a -e $1 && DB_FILE=$1

for table in $(sqlite3 $DB_FILE 'select name from sqlite_master;' | egrep '^sqlite_autoindex|^Core'); do
	DROP="DROP TABLE $table"
	echo $DROP
	sqlite3 $DB_FILE "$DROP" 2>/dev/null
done

