#!/bin/bash

[[ -e "$1" ]] || {
	echo "File does not exist: $1";
	exit 1;
}

for SERVICE_TYPE in Core Extension; do
	echo "$SERVICE_TYPE Services:"
	awk '/'"$SERVICE_TYPE"' service started/{ 
		gsub(/[\(\)\,]/, "")
		gsub(/[0-9]s$/, "")
		print "\t" $7 "\t    " $6
	}' < "$1" | sort -nr
	echo
done


